/* main.js */
import { board, dirTranslation, mapBoard } from "./knightTravails.js";
import { Tree } from "./binary_search_tree.js";

(() => {
  // manual movement
  console.log("Direction: " + board.dir([0, 0], [0, 6]));
  console.log("Direction: " + board.dir([0, 0], [2, 1]));
  console.log("Direction: " + board.dir([0, 0], [1, 2]));
  console.log("Direction: " + board.dir([7, 0], [0, 7]));
  console.log("Direction: " + board.dir([7, 6], [0, 2]));
  console.log("mapBoard[0][0]: " + mapBoard[7][0]);
  console.log("mapBoard[0][0]: " + mapBoard[0][7]);
  console.log("mapBoard[0][0]: " + mapBoard[0][0]);
  console.log("mapBoard[0][0]: " + mapBoard[2][6]);

  let x1;
  let y1;
  let x2;
  let y2;
  let [hyp, deg] = board.getAngle([0, 0], [2, 6]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[0][0]: " + mapBoard[0][0]);
  console.log("mapBoard[2][6]: " + mapBoard[2][6]);
  [hyp, deg] = board.getAngle([0, 7], [0, 1]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[0][7]: " + mapBoard[0][7]);
  console.log("mapBoard[0][1]: " + mapBoard[0][1]);
  [hyp, deg] = board.getAngle([7, 0], [7, 5]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[7][0]: " + mapBoard[7][0]);
  console.log("mapBoard[7][5]: " + mapBoard[7][5]);
  [hyp, deg] = board.getAngle([7, 7], [5, 2]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[7][7]: " + mapBoard[7][7]);
  console.log("mapBoard[5][2]: " + mapBoard[5][2]);
  [hyp, deg] = board.getAngle([0, 0], [5, 2]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[0][0]: " + mapBoard[0][0]);
  console.log("mapBoard[5][2]: " + mapBoard[5][2]);
  [hyp, deg] = board.getAngle([0, 0], [2, 6]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[0][0]: " + mapBoard[0][0]);
  console.log("mapBoard[2][6]: " + mapBoard[2][6]);
  y1 = 7;
  x1 = 0;
  y2 = 5;
  x2 = 6;
  [hyp, deg] = board.getAngle([y1, x1], [y2, x2]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[7][0]: " + mapBoard[y1][x1]);
  console.log("mapBoard[7][5]: " + mapBoard[y2][x2]);
  y1 = 0;
  x1 = 7;
  y2 = 6;
  x2 = 7;
  [hyp, deg] = board.getAngle([y1, x1], [y2, x2]);
  console.log("getAngle1 result, hyp: " + hyp + ", deg: " + deg);
  console.log("mapBoard[7][0]: " + mapBoard[y1][x1]);
  console.log("mapBoard[7][5]: " + mapBoard[y2][x2]);
})();
